@startuml
'https://plantuml.com/class-diagram

class Card {
  - String suit
  - String rank
  - Any value
  .. Getters ..
  + suit
  + rank
  + value
  .. Methods ..
  ctor(object)
  Boolean is(Card card)
  Boolean isSuit(Sring suit)
  Boolean isRank(String rank)
  Boolean isValue(Any value)
  Number compare(Card card)
}


@enduml